services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - portfolio-api_db_vol:/data/db
    networks:
      - portfolio-api_net

  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - portfolio-api_minio_vol:/data
    networks:
      - portfolio-api_net
    command: server /data --console-address ":9001"

networks:
  portfolio-api_net:
    name: portfolio-api_net
    driver: bridge

volumes:
  portfolio-api_db_vol:
  portfolio-api_minio_vol:
